// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type RoleDetail struct {
	ID     sql.NullInt32 `json:"id"`
	Detail string        `json:"detail"`
}

type User struct {
	ID       sql.NullInt32 `json:"id"`
	Username string        `json:"username"`
	Password string        `json:"password"`
	Email    string        `json:"email"`
}

type UserRole struct {
	ID     sql.NullInt32 `json:"id"`
	UserID int32         `json:"user_id"`
	RoleID int32         `json:"role_id"`
}
